version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: H2e3zPzZosaTjOujKL53i9zD0djQam7o
      POSTGRES_DB: travel_planner
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    container_name: spring-backend
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  frontend:
    image: node:20
    container_name: react-frontend
    env_file:
      - .env.frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    command: sh -c "npm install --force && npm start"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=http://localhost:8080
    depends_on:
      - backend

volumes:
  postgres_data:
